server:
  port: 2222
  host_key_path: "./keys/host_rsa"

storage:
  driver: "gcs"
  gcs:
    bucket: "hook22-testing-bucket"
    credentials_file: "./keys/gcp-creds.json"

webhook:
  url: "http://localhost:3000/post"
  secret: "whsec_e2e_secret_999"

users:
  - username: "gcp_test_user"
    password: "gcp_test_password"